// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIStore.Data;

#nullable disable

namespace WebAPIStore.Migrations
{
    [DbContext(typeof(FakeStoreDBContext))]
    partial class FakeStoreDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebAPIStore.Entities.FakeStoreProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("itemName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Category = "men's clothing",
                            Description = "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.",
                            PictureSource = "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
                            Price = 695.0,
                            Quantity = 120,
                            itemName = "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet"
                        },
                        new
                        {
                            Id = 1,
                            Category = "men's clothing",
                            Description = "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
                            PictureSource = "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
                            Price = 109.95,
                            Quantity = 120,
                            itemName = "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops"
                        },
                        new
                        {
                            Id = 2,
                            Category = "men's clothing",
                            Description = "Slim - fitting style, contrast raglan long sleeve, three - button henley placket, light weight & soft fabric for breathable and comfortable wearing.And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans.The Henley style round neckline includes a three - button placket.",
                            PictureSource = "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
                            Price = 22.300000000000001,
                            Quantity = 259,
                            itemName = "Mens Casual Premium Slim Fit T-Shirts "
                        },
                        new
                        {
                            Id = 3,
                            Category = "men's clothing",
                            Description = "great outerwear jackets for Spring / Autumn / Winter, suitable for many occasions, such as working, hiking, camping, mountain / rock climbing, cycling, traveling or other outdoors.Good gift choice for you or your family member.A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.",
                            PictureSource = "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
                            Price = 55.990000000000002,
                            Quantity = 500,
                            itemName = "Mens Cotton Jacket"
                        },
                        new
                        {
                            Id = 4,
                            Category = "men's clothing",
                            Description = "The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.",
                            PictureSource = "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
                            Price = 15.99,
                            Quantity = 430,
                            itemName = "Mens Casual Slim Fit"
                        });
                });

            modelBuilder.Entity("WebAPIStore.Entities.ShoppingCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ShopCartId")
                        .HasColumnType("int");

                    b.Property<string>("modelNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quantity")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("WebAPIStore.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebAPIStore.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("StoreItemId")
                        .HasColumnType("int");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoreItemId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("WebAPIStore.StoreItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StoreItems");
                });

            modelBuilder.Entity("WebAPIStore.ShoppingCart", b =>
                {
                    b.HasOne("WebAPIStore.StoreItems", "StoreItem")
                        .WithMany()
                        .HasForeignKey("StoreItemId");

                    b.Navigation("StoreItem");
                });
#pragma warning restore 612, 618
        }
    }
}
